export const MARATHON_LIST_REQUEST = 'MARATHON_LIST_REQUEST'
export const MARATHON_LIST_SUCCESS = 'MARATHON_LIST_SUCCESS'
export const MARATHON_LIST_FAIL = 'MARATHON_LIST_FAIL'


export const MARATHON_DETAILS_REQUEST = 'MARATHON_DETAILS_REQUEST'
export const MARATHON_DETAILS_SUCCESS = 'MARATHON_DETAILS_SUCCESS'
export const MARATHON_DETAILS_FAIL = 'MARATHON_DETAILS_FAIL'


export const MARATHON_DELETE_REQUEST = 'MARATHON_DELETE_REQUEST'
export const MARATHON_DELETE_SUCCESS = 'MARATHON_DELETE_SUCCESS'
export const MARATHON_DELETE_FAIL = 'MARATHON_DELETE_FAIL'

export const MARATHON_CREATE_REQUEST = 'MARATHON_CREATE_REQUEST'
export const MARATHON_CREATE_SUCCESS = 'MARATHON_CREATE_SUCCESS'
export const MARATHON_CREATE_FAIL = 'MARATHON_CREATE_FAIL'
export const MARATHON_CREATE_RESET = 'MARATHON_CREATE_RESET'


export const MARATHON_UPDATE_REQUEST = 'MARATHON_UPDATE_REQUEST'
export const MARATHON_UPDATE_SUCCESS = 'MARATHON_UPDATE_SUCCESS'
export const MARATHON_UPDATE_FAIL = 'MARATHON_UPDATE_FAIL'
export const MARATHON_UPDATE_RESET = 'MARATHON_UPDATE_RESET'


export const MARATHON_CREATE_REVIEW_REQUEST = 'MARATHON_CREATE_REVIEW_REQUEST'
export const MARATHON_CREATE_REVIEW_SUCCESS = 'MARATHON_CREATE_REVIEW_SUCCESS'
export const MARATHON_CREATE_REVIEW_FAIL = 'MARATHON_CREATE_REVIEW_FAIL'
export const MARATHON_CREATE_REVIEW_RESET = 'MARATHON_CREATE_REVIEW_RESET'

export const MARATHON_TOP_REQUEST = 'MARATHON_TOP_REQUEST'
export const MARATHON_TOP_SUCCESS = 'MARATHON_TOP_SUCCESS'
export const MARATHON_TOP_FAIL = 'MARATHON_TOP_FAIL'

export const MARATHON_CATEGORY_REQUEST = 'MARATHON_CATEGORY_REQUEST'
export const MARATHON_CATEGORY_SUCCESS = 'MARATHON_CATEGORY_SUCCESS'
export const MARATHON_CATEGORY_FAIL = 'MARATHON_CATEGORY_FAIL'

export const MARATHON_LESSON_LIST_REQUEST = 'MARATHON_LESSON_LIST_REQUEST'
export const MARATHON_LESSON_LIST_SUCCESS = 'MARATHON_LESSON_LIST_SUCCESS'
export const MARATHON_LESSON_LIST_FAIL = 'MARATHON_LESSON_LIST_FAIL'

export const MARATHON_LESSON_UPDATE_REQUEST = 'MARATHON_LESSON_UPDATE_REQUEST'
export const MARATHON_LESSON_UPDATE_SUCCESS = 'MARATHON_LESSON_UPDATE_SUCCESS'
export const MARATHON_LESSON_UPDATE_FAIL = 'MARATHON_LESSON_UPDATE_FAIL'


